[2022-11-18 14:37:27,529]: Skip avahi_enable search...
[2022-11-18 14:37:27,530]: SSL is not enabled...
[2022-11-18 14:37:27,533]: [-> CONNECT           ] Connect to Host: 127.0.0.1:11083
[2022-11-18 14:37:34,133]: Ctrl + C Exit
[2022-11-18 14:37:56,601]: Skip avahi_enable search...
[2022-11-18 14:37:56,601]: SSL is not enabled...
[2022-11-18 14:37:56,615]: [-> CONNECT           ] Connect to Host: 127.0.0.1:11083
[2022-11-18 14:37:56,618]: Some error
[2022-11-18 14:37:56,619]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 208, in scan_staff_message
    msg = self._receive_staff_packet()
  File "/home/jyeom/big-thing-py-examples/manager_thing/lora_manager_thing/lora_manager_thing.py", line 101, in _receive_staff_packet
    if self.verify_lora_request_result(lora_device_list):
  File "/home/jyeom/big-thing-py-examples/manager_thing/lora_manager_thing/lora_manager_thing.py", line 132, in verify_lora_request_result
    if type(result_list) == list and 'error' in result_list[0]:
TypeError: argument of type 'int' is not iterable

Error: argument of type 'int' is not iterable
[2022-11-18 14:37:56,619]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 157, in run
    raise Exception('_g_exit was set!!!')
Exception: _g_exit was set!!!

Error: _g_exit was set!!!
[2022-11-18 14:37:58,620]: Traceback message : Traceback (most recent call last):
  File "/home/jyeom/anaconda3/envs/py37tf26/lib/python3.7/site-packages/big_thing_py/manager_thing.py", line 183, in wrapup
    thread.exit()
AttributeError: 'SoPThread' object has no attribute 'exit'

Error: 'SoPThread' object has no attribute 'exit'
